INTERVAL_MIN1 = "minute"
INTERVAL_MIN3 = "3minute"
INTERVAL_MIN5 = "5minute"
INTERVAL_MIN10 = "10minute"
INTERVAL_MIN15 = "15minute"
INTERVAL_MIN30 = "30minute"
INTERVAL_MIN60 = "60minute"
INTERVAL_DAY = "day"

MAX_PERIOD = {
    INTERVAL_MIN1: 60,
    INTERVAL_MIN3: 100,
    INTERVAL_MIN5: 100,
    INTERVAL_MIN10: 100,
    INTERVAL_MIN15: 200,
    INTERVAL_MIN30: 200,
    INTERVAL_MIN60: 400,
    INTERVAL_DAY: 2000,
}

ALL_INTERVALS = MAX_PERIOD.keys()

EXCHANGE_NSE = "NSE"
EXCHANGE_NFO = "NFO"

ALL_EXCHANGES = [
    EXCHANGE_NSE,
    EXCHANGE_NSE,
]

OPTION_TYPE_CALL = "C"
OPTION_TYPE_PUT = "P"

CALL = "CALL"
PUT = "PUT"

CE = "CE"
PE = "PE"

UP = "UP"
DOWN = "DOWN"

DHAN_EXCHANGE_SEGMENTS_ENUM = {
    "IDX_I": 0,
    "NSE_EQ": 1,
    "NSE_FNO": 2,
    "NSE_CURRENCY": 3,
    "BSE_EQ": 4,
    "MCX_COMM": 5,
    "BSE_CURRENCY": 7,
    "BSE_FNO": 8,
}

NIFTY_ITOKEN = 256265

NIFTY50_SYMBOLS = [
    "ADANIENT",
    "ADANIPORTS",
    "APOLLOHOSP",
    "ASIANPAINT",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJAJFINSV",
    "BAJFINANCE",
    "BHARTIARTL",
    "BPCL",
    "BRITANNIA",
    "CIPLA",
    "COALINDIA",
    "DIVISLAB",
    "DRREDDY",
    "EICHERMOT",
    "GRASIM",
    "HCLTECH",
    "HDFCBANK",
    "HDFCLIFE",
    "HEROMOTOCO",
    "HINDALCO",
    "HINDUNILVR",
    "ICICIBANK",
    "INDUSINDBK",
    "INFY",
    "ITC",
    "JSWSTEEL",
    "KOTAKBANK",
    "LT",
    "LTIM",
    "M&M",
    "MARUTI",
    "NESTLEIND",
    "NTPC",
    "ONGC",
    "POWERGRID",
    "RELIANCE",
    "SBILIFE",
    "SBIN",
    "SUNPHARMA",
    "TATACONSUM",
    "TATAMOTORS",
    "TATASTEEL",
    "TCS",
    "TECHM",
    "TITAN",
    "ULTRACEMCO",
    "UPL",
    "WIPRO",
]
