INTERVAL_MIN1 = "minute"
INTERVAL_MIN3 = "3minute"
INTERVAL_MIN5 = "5minute"
INTERVAL_MIN10 = "10minute"
INTERVAL_MIN15 = "15minute"
INTERVAL_MIN30 = "30minute"
INTERVAL_MIN60 = "60minute"
INTERVAL_DAY = "day"

MAX_PERIOD = {
    INTERVAL_MIN1: 60,
    INTERVAL_MIN3: 100,
    INTERVAL_MIN5: 100,
    INTERVAL_MIN10: 100,
    INTERVAL_MIN15: 200,
    INTERVAL_MIN30: 200,
    INTERVAL_MIN60: 400,
    INTERVAL_DAY: 2000,
}

ALL_INTERVALS = MAX_PERIOD.keys()

EXCHANGE_NSE = "NSE"
EXCHANGE_NFO = "NFO"

ALL_EXCHANGES = [
    EXCHANGE_NSE,
    EXCHANGE_NSE,
]

OPTION_TYPE_CALL = "C"
OPTION_TYPE_PUT = "P"
